organizations = [
    {
        '_id': '1',
        'name': 'Golfers Haven Club',
        'image': '/images/golf.jpg',
        'description':
        'Looking for the perfect turf to polish your golfing skills? Look no further than Golfers Haven Club! With our meticulously maintained, sprawling greens and state-of-the-art facilities, we provide an unforgettable golfing experience',
        'brand': 'Apple',
        'game': 'Golf',
        'price': 999.99,
        'countInStock': 10,
        'rating': 4.5,
        'numReviews': 12,
    },
    {
        '_id':'2',
        'name': 'Strikers Paradise',
        'image': '/images/football.jpg',
        'description':
        ' Welcome to Strikers Paradise, the ultimate destination for football enthusiasts! Our cutting-edge turfs, equipped with the latest turf technology, guarantee an exhilarating game every time. Reserve your slot online and make the most of our well-lit, regulation-sized fields.',
        'brand': 'Apple',
        'game': 'Football',
        'price': 799.99,
        'countInStock': 7,
        'rating': 4.0,
        'numReviews': 8,
    },
    {
        '_id': '3',
        'name': 'Ace Arena Tennis Club',
        'image': '/images/tennis.jpg',
        'description':
        'Serve, volley, and ace your way to victory at Ace Arena Tennis Club! With our premium-quality turf courts, designed to meet professional standards, we offer an ideal setting for tennis aficionados of all levels. Book your court online and immerse yourself in the thrill of the game',
        'brand': 'Cannon',
        'game': 'Tennis',
        'price': 1229.99,
        'countInStock': 5,
        'rating': 3,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Riders Roost Equestrian Club',
        'image': '/images/equestrian.jpg',
        'description':
        ' Saddle up and experience the thrill of horseback riding at Riders Roost Equestrian Club! Our well-maintained equestrian turfs, nestled amidst breathtaking natural landscapes, provide a picturesque setting for riders of all ages and skill levels',
        'brand': 'Sony',
        'game': 'Equestrian',
        'price': 3099.99,
        'countInStock': 11,
        'rating': 5,
        'numReviews': 12,
    },
    {
        '_id': '4',
        'name': 'Hoopers Hangout Basketball Club',
        'image': '/images/basketball.jpg',
        'description':
        'Calling all basketball lovers! Hoopers Hangout Basketball Club offers top-notch turfs for a thrilling game of hoops. With our meticulously maintained courts, equipped with high-quality backboards and lighting, we ensure an optimal playing experience for all basketball enthusiasts. Book your court online and enjoy our professional-grade facilities, expert coaching, and a vibrant community that fosters teamwork and friendly competition',
        'brand': 'Logitech',
        'game': 'BasketBall',
        'price': 849.99,
        'countInStock': 7,
        'rating': 3.5,
        'numReviews': 10,
    },
    {
        '_id': '5',
        'name': 'Ace Archers Club',
        'image': '/images/archery.jpg',
        'description':
        'Take aim and perfect your archery skills at Ace Archers Club! Our specialized turfs provide the ideal environment for archery aficionados to practice and compete. Reserve your spot online and benefit from our well-equipped ranges, personalized coaching, and a supportive community of fellow archers',
        'brand': 'Amazon',
        'game': 'Archery',
        'price': 1699.99,
        'countInStock': 0,
        'rating': 4,
        'numReviews': 12,
    },
]
