export const FILTER_CLUB_REQUEST = 'FILTER_CLUB_REQUEST'
export const FILTER_CLUB_SUCCESS = 'FILTER_CLUB_SUCCESS'
export const FILTER_CLUB_FAIL = 'FILTER_CLUB_FAIL'

export const CLUB_LIST_REQUEST = 'CLUB_LIST_REQUEST'
export const CLUB_LIST_SUCCESS = 'CLUB_LIST_SUCCESS'
export const CLUB_LIST_FAIL = 'CLUB_LIST_FAIL'

export const CLUB_DETAIL_REQUEST = 'CLUB_DETAIL_REQUEST'
export const CLUB_DETAIL_SUCCESS = 'CLUB_DETAIL_SUCCESS'
export const CLUB_DETAIL_FAIL = 'CLUB_DETAIL_FAIL'

export const CLUB_LOCATION_REQUEST = 'CLUB_LOCATION_REQUEST'
export const CLUB_LOCATION_SUCCESS = 'CLUB_LOCATION_SUCCESS'
export const CLUB_LOCATION_FAIL = 'CLUB_LOCATION_FAIL'
export const CLUB_GAME_REQUEST = 'CLUB_GAME_REQUEST'
export const CLUB_GAME_SUCCESS = 'CLUB_GAME_SUCCESS'
export const CLUB_GAME_FAIL = 'CLUB_GAME_FAIL'
export const CLUB_AMENITIES_REQUEST = 'CLUB_AMENITIES_REQUEST'
export const CLUB_AMENITIES_SUCCESS = 'CLUB_AMENITIES_SUCCESS'
export const CLUB_AMENITIES_FAIL = 'CLUB_AMENITIES_FAIL'
export const CLUB_WORKING_REQUEST = 'CLUB_WORKING_REQUEST'
export const CLUB_WORKING_SUCCESS = 'CLUB_WORKING_SUCCESS'
export const CLUB_WORKING_FAIL = 'CLUB_WORKING_FAIL'

export const CLUB_IMAGE_REQUEST = 'CLUB_IMAGES_REQUEST'
export const CLUB_IMAGE_SUCCESS = 'CLUB_IMAGES_SUCCESS'
export const CLUB_IMAGE_FAIL = 'CLUB_IMAGES_FAIL'

export const GAME_LIST_REQUEST = 'GAME_LIST_REQUEST'
export const GAME_LIST_SUCCESS = 'GAME_LIST_SUCCESS'
export const GAME_LIST_FAIL = 'GAME_LIST_FAIL'

export const AREA_LIST_REQUEST = 'AREA_LIST_REQUEST'
export const AREA_LIST_SUCCESS = 'AREA_LIST_SUCCESS'
export const AREA_LIST_FAIL = 'AREA_LIST_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL';
export const BOOKING_CREATE_RESET = 'BOOKING_CREATE_RESET';

export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST';
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS';
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL';

export const BOOKING_LIST_REQUEST = 'BOOKING_LIST_REQUEST';
export const BOOKING_LIST_SUCCESS = 'BOOKING_LIST_SUCCESS';
export const BOOKING_LIST_FAIL = 'BOOKING_LIST_FAIL';

export const COURT_LIST_REQUEST = 'COURT_LIST_REQUEST';
export const COURT_LIST_SUCCESS = 'COURT_LIST_SUCCESS';
export const COURT_LIST_FAIL = 'COURT_LIST_FAIL';

export const AVAILABLE_SLOT_REQUEST = 'AVAILABLE_SLOT_REQUEST';
export const AVAILABLE_SLOT_SUCCESS = 'AVAILABLE_SLOT_SUCCESS';
export const AVAILABLE_SLOT_FAIL = 'AVAILABLE_SLOT_FAIL';