# Generated by Django 5.0.1 on 2024-02-20 09:02

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_organizationgameimages_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationgameimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.get_organization_image_upload_path),
        ),
    ]
