# Generated by Django 3.2.20 on 2024-03-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.organizationlocationgametype'),
        ),
    ]
