# Generated by Django 3.2.20 on 2024-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_court_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlocationgametype',
            name='number_of_courts',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'), (6, 'six'), (7, 'seven'), (8, 'eight'), (9, 'nine'), (10, 'ten')], default=1),
        ),
    ]
