# Generated by Django 3.2.20 on 2024-02-28 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_organizationgameimages_image'),
        ('booking', '0002_auto_20240228_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.gametype'),
        ),
    ]
