# Generated by Django 3.2.20 on 2024-03-01 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_court'),
        ('booking', '0004_auto_20240229_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.court'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.court'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Court',
        ),
    ]
