# Generated by Django 3.2.20 on 2024-03-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_court'),
        ('booking', '0005_auto_20240301_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.organizationlocation'),
            preserve_default=False,
        ),
    ]
