# Generated by Django 3.2.20 on 2024-03-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_slot_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='date',
        ),
        migrations.AddField(
            model_name='slot',
            name='days',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
