# Generated by Django 3.2.20 on 2024-03-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_slot_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
